name: Check Documentation Update

on:
  push:
    branches:
      - main  # or specify other branches you want to check

jobs:
    build: 
        name: test
   check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history to ensure previous commits and branches are available

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if Documentation is Updated
        run: |
          if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
              DIFF_TARGET="HEAD~1"
          else
              DIFF_TARGET="origin/main"
          fi
          if git diff --name-only $DIFF_TARGET HEAD | grep -q '^docs/'; then
              echo "Documentation updated."
          else
              echo "::error::Documentation in 'docs/' folder is not updated! Please update documentation before committing."
              exit 1
          fi
